### ISSUE TITLE
 Read the pedigree string and assign parents

### ISSUE THREAD

**Issue by jcdpineda** [plantbreeding/brapi-Java-TestServer#55]
When doing a POST /germplasm, it would be nice if individual parent information are also populated in the `pedigree` table, and also be able to display the information in the GET /germplasm endpoint:

```
[
  {
    "germplasmName": "Tomato",
    ...
    "pedigree": {
        "pedigreeDbId": "a5629d27-947c-4bcf-b776-f05f85b5e899",
        "pedigree": "parent1/parent2",
        "parent1Id": "433971ba-87b5-446a-bfdb-dd8206981817",
        "parent1Name": "parent1",
        "parent2Id": "fb1ca2ff-e1ce-452a-b8bf-ed815b8e2017",
        "parent2Name": "parent2",    
     }
  }
]
```

**Comment by BrapiCoordinatorSelby** [comment]
partially fixed in commit 42922caf9b634b9241234cc7b7333ca3aeddc542 

You can now use `POST /germplasm` to set and `PUT /germplasm` to modify the pedigree tree using the `pedigree` string field. The system will read the pedigree string and check for any germplasmDbId, germplasmName, synonyms, and accessionNumbers that match the values in the string. The first matching germplasm in the database is taken as the parent DbId.

The second half of this issue references changing the response structure of  `GET /germplasm`. I cannot do this on the BrAPI test server because it would require a change to the BrAPI specification. @jcdpineda if you would like to see this functionality added to a future version of the BrAPI specification, please open a new issue in https://github.com/plantbreeding/BrAPI/issues or add a comment to https://github.com/plantbreeding/BrAPI/issues/481

**Comment by jcdpineda** [comment]
Thanks @BrapiCoordinatorSelby ! If a parent from the pedigree string has no matching record in the germplasm table, will a new germplasm record be created for that parent?

I may have missed something, but I was under the impression that the addition of `parent1Id` and `parent2Id` to the GET /germplasm response structure will be addressed in this issue -> https://github.com/plantbreeding/BrAPI/issues/481

```
[
    {
        "germplasmDbId": "001",
        "germplasmName": "Tomato",
        "pedigree": "parent1/parent2"
        "parent1_id": "1001"
        "parent2_id": "1002"
    }
]
```
If not I will create another issue.

Thanks!

**Comment by BrapiCoordinatorSelby** [comment]
@jcdpineda 
Aah I see what you mean. My confusion was that in plantbreeding/BrAPI#481 you were talking about the endpoint `GET /germplasm/germplasmDbId/pedigree` but in this issue you were talking about `GET /germplasm` 

To be perfectly clear
`GET /germplasm/germplasmDbId/pedigree` already has all the information you list above (gemplasm, pedigree string, and parents) 
`GET /germplasm` only has the germplasm, and pedigree string. 
You want to add a `parents` array to the main `GET /germplasm` response. It must be an array because there can be more than 2 parents in some cases.

Is this correct? If yes, then I will add all this as a clarifying comment to plantbreeding/BrAPI#481 to make sure it is done correctly

**Comment by jcdpineda** [comment]
@BrapiCoordinatorSelby 

> GET /germplasm/germplasmDbId/pedigree already has all the information you list above (gemplasm, pedigree string, and parents)

Indeed, I missed this in the docs. Thanks for the clarification! Therefore, when I do a `POST /germplasm`, and the parent from the pedigree string has no matching germplasm record, will a new germplasm record be created for that parent?

> You want to add a parents array to the main GET /germplasm response. It must be an array because there can be more than 2 parents in some cases.

Yes, this is what we are thinking. I may have not explained it properly earlier, but we ultimately want to be able to retrieve the complete the pedigree information of a certain crop/population, in order to generate pedigree-based relationship matrices. A simple `GET /germplasm` can already do this since it returns all germplasms and corresponding pedigree strings. 

However, we want to be able to filter the results according to  `commonCropNames`, `familyCode`, `instituteCode`, using using the `POST /search/germplasm` endpoint:

```
[
    "commonCropNames": ["Tomato"],
    "familyCode": ["001", "002", "003"]
    "instituteCode": ["BRP"],
]
```
Is this actually feasible?

**Comment by BrapiCoordinatorSelby** [comment]
> when I do a `POST /germplasm`, and the parent from the pedigree string has no matching germplasm record, will a new germplasm record be created for that parent?

No, I did not setup the BrAPI test server to create a new germplasm record for a missing parent. From a technical perspective, you could do this, but it seems risky to me to create a new germplasm entity based only on the name with no other details. You could instead do `POST /germplasm` with the child details, then if the parent is not present `POST /germplasm` with the parent details, then `PUT /germplasm/child` to update the child pedigree to re-scan and connect with the now existing parent record. something like that allows for more flexibility and control for the client to decide how to manage germplasm. 

>Is this actually feasible?

yes this is feasible. please add this as a comment in plantbreeding/BrAPI#481 so in a month from now I be able to remember exactly the new search fields you want.

**Comment by jcdpineda** [comment]
@BrapiCoordinatorSelby 

The docs doesn't seem to have a `PUT /germplasm/child`. I also see that there is a `GET /progeny` endpoint. Is there a `POST /progeny` too?

**Comment by BrapiCoordinatorSelby** [comment]
> The docs doesn't seem to have a `PUT /germplasm/child`.

@jcdpineda I'm sorry for the misunderstanding. I meant use the endpoint `PUT /germplasm/germplasmDbId` with the DbId for the child germplasm.

> I also see that there is a GET /progeny endpoint. Is there a POST /progeny too?

no, and there probably won't be. `POST /pedigree` and `POST /progeny` would look almost identical. Each would need to send a list of germplasmDbIds with links to the parent DbIds. Adding new nodes to the pedigree tree requires the same information for each node regardless of the direction you are building.
