### ISSUE TITLE
Integration with Breedbase

### ISSUE THREAD

**Issue by jcdpineda** [plantbreeding/brapi-Java-TestServer#57]
Hi @BrapiCoordinatorSelby ,

In the Brapi Test Server, uploading germplasm data (via POST /germplasm) does not require `location`-related attributes. I am wondering: will there be issues when, say, we want to transfer/communicate data from the Brapi Test Server to Breedbase? If I am not mistaken, Breedbase requires the location in order for the data to be uploaded.

**Comment by BrapiCoordinatorSelby** [comment]
to clarify, when you say location related attributes, do you mean `germplasmOrigin` and `instituteName` in the Germplasm object model, or do you mean a BrAPI Location object? Either way, I would double check if those things are required in Breedbase because I've never heard anything like that.

Generally speak, yes this kind of incompatibility can happen. Most of the fields in the BrAPI spec are considered optional, but different tools and databases will enforce data requirements depending on their own situations. We can't enforce required fields at the specification level because each group will have different data they can provide. So required fields must be enforced at the application/server level. 
When you have two applications with conflicting required fields, like your example, then we have to start negotiating. In this example, either Breedbase needs to change to accept Germplasm without location info, or the Test Server has to change to require location info, or at least warn the user that certain Germplasm won't be transferred. 
The BrAPI spec provides a common language, but that negotiation/problem solving process still needs to happen for specific use cases. 

I like keeping the Test Server pretty open and unrestricted. Its primary purpose is to be able to accept data from as many different sources as possible for testing. If you have a use case where you need to transfer germplasm to Breedbase, but its not working, we should talk to the Breedbase team to find a solution together.
